services:
  database:
    image: postgres:16
    container_name: goteste
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sistema
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data